### PR TITLE
FreeBSD support

### PR DESCRIPTION
**Pull request by jbeich**
Depends on #292. Runtime tested via [i965](https://www.freshports.org/multimedia/libva-intel-driver), [iHD](https://www.freshports.org/multimedia/libva-intel-media-driver)+[QSV](https://www.freshports.org/multimedia/intel-media-sdk) and `radeonsi` from Mesa.

### CODE REVIEW

**Comment by jbeich** [comment]
@niacat, can you try building Wayland backend on NetBSD?
@iarebatman, I've salvaged useful bits from #350. Can you recheck?

**Comment by niacat** [comment]
@jbeich Seems to build successfully with -Dwayland=yes on NetBSD. Haven't tested it, but these files are generated:

~~~
./output/va/198dea3@@va-wayland@sha/wayland_va_wayland.c.o
./output/va/198dea3@@va-wayland@sha/wayland_va_wayland_drm.c.o
./output/va/198dea3@@va-wayland@sha/wayland_va_wayland_emgd.c.o
~~~

**Comment by jbeich** [comment]
Sorry, I'm going to rebase in order to unbreak TravisCI in media-driver.

File: .travis.yml [hunk 1]
```diff
@@ -62,6 +62,19 @@ script:
...
+    - os: linux
+    - os: freebsd
+      compiler: clang
+      before_install:
+        - sudo pkg install -y meson pkgconf libdrm libXext libXfixes wayland
+        - sudo pkg install -y -x '^mesa($|-libs)'
+      script:
+        - meson build
+        - ninja -C build
+      after_success: true
```
Comment (jbeich) [inline .travis.yml:76]: `true` here because empty values produces errors:
```
/home/travis/build.sh: line 1436: travis_run_after_success: command not found
/home/travis/build.sh: line 1437: travis_run_after_failure: command not found
/home/travis/build.sh: line 1438: travis_run_after_script: command not found
/home/travis/build.sh: line 1439: travis_run_finish: command not found
```

**Comment by jbeich** [comment]
What would it take to merge this? I'm not affiliated with any vendor, so can't negotiate through sales. DragonFly, FreeBSD, NetBSD have VAAPI enabled in binary packages for years. Transcoding in Plex using VAAPI (libva but not libmfx) is popular among FreeNAS users.

libva, libva-utils, intel-vaapi-driver are already somewhat portable and don't change much, so the maintanence should be low.

**Review by dvrogozh — COMMENTED** [review]
Thank you for upstreaming BSD changes!

Initial PR description says that this PR depends on #292. Is that still true or #363 became self-sufficient?

Effectively I have nothing against merging this in. The only question I have is: who can be a contact point in case more changes will be needed or some questions will arise? I wish we had some kind of file like MAINTANERS or OWNERS or whatever (might be wiki article) listing whom people can contact w/ different questions.

**Comment by jbeich** [comment]
> Initial PR description says that this PR depends on #292. Is that still true or #363 became self-sufficient?

#292 is still necessary but it's a runtime fix (used by `mpv --gpu-context=drm` and encoding) with small risk. This PR contains only build-related changes with zero risk (after passing CI).

> who can be a contact point in case more changes will be needed or some questions will arise?

Downstream package maintainer (currently, @jbeich) or [FreeBSD graphics team/maillist](mailto:x11@FreeBSD.org) (e.g., @evadot, @zeising, @myfreeweb).

**Review by dvrogozh — APPROVED** [review]

**Comment by jbeich** [comment]
I've rebased to avoid noise from merge commits (TravisCI build didn't start, anyway). Please, don't squash on PR merge as it'd make bisecting and/or cherry-picking harder.

**Comment by dvrogozh** [comment]
Thx. No, I don't like squashing either. @jbeich : did you have travis ci passing at some point? /I'll give it couple of hours in hope it will work, but will merge if it won't. If you will note that you had it working - this will give me some confidence:)./

**Comment by jbeich** [comment]
> did you have travis ci passing at some point?

From https://travis-ci.org/github/intel/libva/pull_requests 

https://travis-ci.org/github/intel/libva/builds/732134798
https://travis-ci.org/github/intel/libva/builds/727005698
https://travis-ci.org/github/intel/libva/builds/720179146
https://travis-ci.org/github/intel/libva/builds/717845645
https://travis-ci.org/github/intel/libva/builds/711657033
[...]

**Comment by jbeich** [comment]
Same commit on TravisCI:
- https://travis-ci.com/github/jbeich/libva/builds/190333830 (completed 3 hours ago)
- https://travis-ci.org/github/intel/libva/builds/736158389 (still waiting)

**Comment by jbeich** [comment]
Hmm, 6e3798a72b isn't in my fork. What TravisCI is testing then?

**Comment by dvrogozh** [comment]
This builds ok on freebsd: https://github.com/dvrogozh/libva/actions/runs/311038053. Let's try to merge this in. There is a risk that travis CI is not enabled correctly for freebsd, but we can deal with this separately.

**Comment by uartie** [comment]
This breaks build on ubuntu focal (20.04):
```
17:05:59,298 INFO  - va_trace.c:67:14: error: static declaration of ‘gettid’ follows non-static declaration
17:05:59,299 INFO  - 67 | static pid_t gettid()
17:05:59,299 INFO  - | ^~~~~~
17:05:59,299 INFO  - In file included from /usr/include/unistd.h:1170,
17:05:59,299 INFO  - from va_trace.c:48:
17:05:59,299 INFO  - /usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of ‘gettid’ was here
17:05:59,299 INFO  - 34 | extern __pid_t gettid (void) __THROW;
17:05:59,299 INFO  - | ^~~~~~
```

**Comment by uartie** [comment]
... and Fedora builds broken too
