### ISSUE TITLE
fatal error: va/va_dec_av1.h: No such file or directory

### ISSUE THREAD

**Issue by uartie** [intel/libva#382]
Software that includes installed `va/va.h` can't compile: `va/va.h:4630:10: fatal error: va/va_dec_av1.h: No such file or directory`. Did you forget to add an install target for `va_dec_av1.h` for the automake toolchain?

This issue was introduced with #317
